### ISSUE TITLE
Can't change profile picture

### ISSUE THREAD

**Issue by nfrelink** [GabrielTenma/lightdm-gab-gradient#1]
I've added my profile picture into the html code, in the `<img id="login-picture">` field so it becomes `<img id="login-picture" src="img.png">`. My picture shows up for half a second and then fades away to white. Commenting out `-webkit-transition:opacity .5s ease-in-out;` in the style.css file doesn't help either.

**Comment by voxain** [comment]
This is because the theme automatically loads the user picture you saved for your account. Most of the time, there is a UI where you can set yoir user data - e.g. In Manjaro, you just open your start menu and click on your user name which appers somewhere there.

If that's not the case, you can just save an image called `.face` in yoir home directory - the theme automatically loads this as soon as you try to login with your username.

**Comment by nfrelink** [comment]
Aah I see, I was able to change it. Thanks for the quick reply!
